server:
  port: 8088
  tls:
    enabled: false
    cert_file: "tls/cert.pem"
    key_file: "tls/key.pem"

load_balancer:
  strategy: "least-connections"  # Options: round-robin, least-connections, ip-hash
  backends:
    - "http://localhost:8000"
    - "http://localhost:8008"
